flowchart TD
    README["README<br/>1 funcs"]
    SUMD["SUMD<br/>150 funcs"]
    docs__API["docs.API<br/>1 funcs"]
    docs__README["docs.README<br/>1 funcs"]
    project__map["project.map<br/>150 funcs"]
    src__opstree["src.opstree<br/>129 funcs"]
