"""Migration YAML format adapter — read/write redeploy-compatible migration.yaml."""
from __future__ import annotations
from typing import Any, Dict
from opstree.snapshot.model import Snapshot, PartialSnapshot, LayerData
from datetime import datetime
import yaml


class MigrationYamlAdapter:
    """Parsuj i emituj migration.yaml (redeploy-compatible)."""
    format_name = "migration_yaml"
    
    def parse(self, text: str) -> PartialSnapshot:
        """Parsuj migration.yaml → PartialSnapshot."""
        data = yaml.safe_load(text)
        layers = {}
        
        # Parse source/target metadata
        source = data.get("source", {})
        target = data.get("target", {})
        
        if source:
            layers["runtime.container"] = LayerData(
                layer_id="runtime.container",
                probed_at=datetime.utcnow(),
                probed_by="migration_yaml_parser",
                data={
                    "runtime": source.get("strategy", "unknown"),
                    "version": source.get("version", "unknown"),
                    "environment_name": source.get("host", "unknown"),
                },
            )
        
        if target:
            layers["endpoint.http"] = LayerData(
                layer_id="endpoint.http",
                probed_at=datetime.utcnow(),
                probed_by="migration_yaml_parser",
                data={
                    "endpoints": [{
                        "url": target.get("verify_url", ""),
                        "target": target.get("host", "unknown"),
                        "domain": target.get("domain", ""),
                    }],
                },
            )
            
            layers["business.health"] = LayerData(
                layer_id="business.health",
                probed_at=datetime.utcnow(),
                probed_by="migration_yaml_parser",
                data={
                    "app_name": target.get("app", "unknown"),
                    "app_version": target.get("version", "0.0.0"),
                    "overall_health": "unknown",
                    "alerts": [],
                },
            )
        
        return PartialSnapshot(
            layers=layers,
            source_format="migration_yaml",
            source_path=None,
        )
    
    def render(self, snapshot: Snapshot | PartialSnapshot) -> str:
        """Renderuj Snapshot → migration.yaml."""
        runtime_layer = snapshot.layers.get("runtime.container")
        endpoint_layer = snapshot.layers.get("endpoint.http")
        business_layer = snapshot.layers.get("business.health")
        
        # Build migration.yaml structure
        migration = {
            "name": business_layer.data.get("app_name", "unknown") + "-migration" if business_layer else "unknown",
            "description": "Migration generated by op3",
            
            "source": {
                "strategy": runtime_layer.data.get("runtime", "docker_full") if runtime_layer else "docker_full",
                "host": runtime_layer.data.get("environment_name", "local") if runtime_layer else "local",
                "app": business_layer.data.get("app_name", "unknown") if business_layer else "unknown",
                "version": business_layer.data.get("app_version", "0.0.0") if business_layer else "0.0.0",
            } if runtime_layer or business_layer else {},
            
            "target": {
                "strategy": "podman_quadlet",
                "host": "localhost",
                "app": business_layer.data.get("app_name", "unknown") if business_layer else "unknown",
                "version": business_layer.data.get("app_version", "0.0.0") if business_layer else "0.0.0",
            } if business_layer else {},
            
            "extra_steps": [],
            
            "notes": ["Generated by op3 from snapshot"],
        }
        
        # Add endpoint info if available
        if endpoint_layer:
            endpoints = endpoint_layer.data.get("endpoints", [])
            if endpoints:
                ep = endpoints[0]
                if "target" in migration:
                    migration["target"]["host"] = ep.get("target", "localhost")
                if "domain" in ep:
                    migration["target"]["domain"] = ep["domain"]
                if "url" in ep:
                    migration["target"]["verify_url"] = ep["url"]
        
        return yaml.dump(migration, sort_keys=False, default_flow_style=False)
